# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rama/Desktop/CPP/4PMultiplayerGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rama/Desktop/CPP/4PMultiplayerGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rama/Desktop/CPP/4PMultiplayerGame/CMakeFiles /home/rama/Desktop/CPP/4PMultiplayerGame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rama/Desktop/CPP/4PMultiplayerGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fpmpg

# Build rule for target.
fpmpg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fpmpg
.PHONY : fpmpg

# fast build rule for target.
fpmpg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/build
.PHONY : fpmpg/fast

Connection.o: Connection.cpp.o
.PHONY : Connection.o

# target to build an object file
Connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/Connection.cpp.o
.PHONY : Connection.cpp.o

Connection.i: Connection.cpp.i
.PHONY : Connection.i

# target to preprocess a source file
Connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/Connection.cpp.i
.PHONY : Connection.cpp.i

Connection.s: Connection.cpp.s
.PHONY : Connection.s

# target to generate assembly for a file
Connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/Connection.cpp.s
.PHONY : Connection.cpp.s

Test.o: Test.cpp.o
.PHONY : Test.o

# target to build an object file
Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/Test.cpp.o
.PHONY : Test.cpp.o

Test.i: Test.cpp.i
.PHONY : Test.i

# target to preprocess a source file
Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/Test.cpp.i
.PHONY : Test.cpp.i

Test.s: Test.cpp.s
.PHONY : Test.s

# target to generate assembly for a file
Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/Test.cpp.s
.PHONY : Test.cpp.s

WebQueue.o: WebQueue.cpp.o
.PHONY : WebQueue.o

# target to build an object file
WebQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/WebQueue.cpp.o
.PHONY : WebQueue.cpp.o

WebQueue.i: WebQueue.cpp.i
.PHONY : WebQueue.i

# target to preprocess a source file
WebQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/WebQueue.cpp.i
.PHONY : WebQueue.cpp.i

WebQueue.s: WebQueue.cpp.s
.PHONY : WebQueue.s

# target to generate assembly for a file
WebQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpmpg.dir/build.make CMakeFiles/fpmpg.dir/WebQueue.cpp.s
.PHONY : WebQueue.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fpmpg"
	@echo "... Connection.o"
	@echo "... Connection.i"
	@echo "... Connection.s"
	@echo "... Test.o"
	@echo "... Test.i"
	@echo "... Test.s"
	@echo "... WebQueue.o"
	@echo "... WebQueue.i"
	@echo "... WebQueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

